---

- name: Hello, World!
  command: "echo {{ item }}"
  with_items:
    - "Hello,"
    - "World"

- name: Install packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - nginx
    - httpd
    - rkhunter
